### ISSUE TITLE
Implement email campaign (consumer opt-in)

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/litmus-sg-project-2#1]
@codextiny 
Please implement these 4 templates as a new campaign in SendGrid with our new standardized template. [https://docs.google.com/document/d/109zA7xpkM9qrVQnPsP5Syu528YMxSXvX03tyVcOiprE/edit?usp=sharing](url)

**Comment by shannonbaldwin** [comment]
@codextiny 
Template ID: Reminder 1: d-e71a4b9ce41f4255883001b9ad122211![image](https://github.com/shannonbaldwin/litmus-sg-project-2/assets/167017886/77412aea-b887-4fac-920e-5e1c9a480c82)

**Comment by shannonbaldwin** [comment]
@codextiny
Template ID:

1. Fonts are not consistent with new standardized template. 
![image](https://github.com/shannonbaldwin/litmus-sg-project-2/assets/167017886/6ef6449d-893c-4ad7-9b0b-47222ea3a9a8)
2. "portal" is misspelled.
![image](https://github.com/shannonbaldwin/litmus-sg-project-2/assets/167017886/ff5abfe6-5107-40e2-94b7-13a5a379dfb8)

**Comment by shannonbaldwin** [comment]
@codextiny
Template ID: d-b055ef3d972645968f20ebd34e6e778b

1. Same font/footer issues as above![image](https://github.com/shannonbaldwin/litmus-sg-project-2/assets/167017886/f40a6346-abc6-4c30-9433-c302c4b4d881)

2. See content changes in subject line and body of email in the google doc [https://docs.google.com/document/d/109zA7xpkM9qrVQnPsP5Syu528YMxSXvX03tyVcOiprE/edit](url)

**Comment by shannonbaldwin** [comment]
@codextiny 
Template ID: d-f098204e44274dd081eed9da25f6cfab 

1. Error on third bullet point. See google doc ![image](https://github.com/shannonbaldwin/litmus-sg-project-2/assets/167017886/2f3e03dc-94ac-441d-a852-42b825a1b781)

**Comment by shannonbaldwin** [comment]
@codextiny please make sure all preview text is uploaded according to google doc

**Comment by codextiny** [comment]
@shannonbaldwin 

All points are done, please check.
