### ISSUE TITLE
Onboarding Campaign #3

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/litmus-sg-project-2#2]
@codextiny 

Please correct below and see [google doc](https://docs.google.com/document/d/1fWC7NoYjCbU2WLFj7qzXZTZamea4L2Rjk6X9DXd2-e8/edit) for reference:

1. Template ID:d-a423f2b517e846089d90406524f3c0ee (both V1 and V2). This first sentence is missing from both versions. ![image](https://github.com/user-attachments/assets/b925bf27-d674-475c-b25b-814da2a16354)

2. Template ID: d-2f3edbb49a1847338b0ba50f021a6078  bold and italicize this word in both versions.

 ![image](https://github.com/user-attachments/assets/34883d46-3a23-4af5-a242-bfa408964bc7)

**Comment by codextiny** [comment]
@shannonbaldwin 

fixed, please check
